[versions]
projektor = "4.+"

kotlin = "2.0.21"

lapis-api = "0.5.0"

[plugins]
projektor = { id = "io.github.diskria.projektor", version.ref = "projektor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
lapis-api = { group = "io.github.recrafter", name = "lapis-api", version.ref = "lapis-api" }
